jobs:
  tests-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install project + dev deps
        working-directory: assignments
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: run tests
        working-directory: assignments
        run: |
          python -m pytest life_expectancy --cov

      - name: run pylint
        working-directory: assignments
        run: |
          pylint life_expectancy.cleaning
